steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/backend:$COMMIT_SHA
      - .

    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/backend:$COMMIT_SHA

  - name: "gcr.io/$PROJECT_ID/helm"
    args:
      - upgrade
      - --install
      - backend
      - charts/backend
      - --set
      - image.repository=gcr.io/$PROJECT_ID/backend
      - --set
      - image.version=$COMMIT_SHA
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_REGION"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER"
      - "HELM_REPO_NAME=charts"
      - "HELM_REPO_URL=https://my-devprod-vps-helm-charts.storage.googleapis.com/"
      - "TILLERLESS=true"

substitutions:
  _REGION: europe-north1
  _CLUSTER: lab-evlsrv-notejam-cluster
